#!/usr/bin/env bash
# Copy a single file
# scp localmachine/path_to_the_file username@server_ip:/path_to_remote_directory
# scp /home/emma/ALX/tests/first.js ubuntu@100.26.235.150:~

#Copy a dir
# scp -r localmachine/path_to_the_file username@server_ip:/path_to_remote_dir/
# source dir dont have / at the end but destination path must have

# Copy all files in local dir to remote dir
# scp -r localmachine/path_to_the_file/* username@server_ip:/path_to_remote_dir/

# check if paramaters are 4
if [ "$#" -ne 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
else
  PATH_TO_FILE="$1"
  IP="$2"
  USERNAME="$3"
  PATH_TO_SSH_KEY="$4"
  scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~"
fi
