#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server

sudo apt -y update
sudo apt install -y haproxy
sudo service haproxy start
sudo echo "frontend techactuary
	# maps all requests for port 80    
	bind *:80
	default_backend backend_techactuary

backend backend_techactuary
	balance roundrobin
	server 307299-web-01 100.26.235.150:80 check
	server 307299-web-02 18.206.208.35:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo systemctl enable haproxy
sudo service haproxy restart
