#!/usr/bin/env bash

# Check if the MySQL password argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <MySQL Password>"
  exit 1
fi

# Create a MySQL dump for all databases and save it as "backup.sql"
mysqldump -uroot -p"$1" --all-databases > backup.sql

# Create a compressed archive with the specified format
tar -czf "$(date +%d-%m-%Y)".tar.gz backup.sql
#tar -czf $(date +%d-%m-%m).tar.gz backup.sql
