#!/usr/bin/env bash
# display time for 12 hours and 59 minutes
hour=0
while ((hour <= 12))
do
	echo "Hour: $hour"
	counter="1"	
	while ((counter < 60))
	do
		echo "$counter"
		((counter++))
	done
	((hour++))
done	
