#!/usr/bin/env bash
# Your machine has an SSH configuration file for the local SSH client, let's configure it to our needs so that you can connect to a server without typing a password. Share your SSH client configuration in your answer file.

Host 100.25.135.51 IdentifyFile ~/.ssh/school PasswordAuthentication no
